### ISSUE TITLE
không cài được cho laravel/framework v7.17.1

### ISSUE THREAD

**Issue by khanhnam99** [phpviet/laravel-validation#5]
pagekage này không cài được  laravel v7.17.1

![Capture](https://user-images.githubusercontent.com/575720/85651518-73c68980-b6d2-11ea-9b4d-cd5fe2fe32f1.PNG)

**Comment by vuongxuongminh** [comment]
Đã hổ trợ, bạn test lại nha. Cảm ơn bạn đã report.
